# Generated by Django 5.2.7 on 2025-11-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioGerencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relatorio', models.CharField(max_length=50)),
                ('data_referencia', models.DateField()),
                ('total_ocorrencias', models.IntegerField(blank=True, null=True)),
                ('estatistica_tipo', models.JSONField()),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Relatório Gerencial',
                'verbose_name_plural': 'Relatórios Gerenciais',
                'db_table': 'dashboard_relatorio_gerencial',
            },
        ),
    ]
