# Generated by Django 5.2.7 on 2025-11-02 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipePlantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtr_sigla', models.CharField(max_length=20, verbose_name='Sigla VTR')),
                ('data_plantao', models.DateField()),
                ('condutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipes_como_condutor', to=settings.AUTH_USER_MODEL)),
                ('enfermeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipes_como_enfermeiro', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipes_como_medico', to=settings.AUTH_USER_MODEL)),
                ('tecnico_enf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipes_como_tecnico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipe de Plantão',
                'verbose_name_plural': 'Equipes de Plantão',
                'db_table': 'plantao_equipe_plantao',
                'unique_together': {('vtr_sigla', 'data_plantao')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('vtr_observacao', models.TextField(blank=True, null=True, verbose_name='Observações da VTR')),
                ('foto_vtr', models.ImageField(blank=True, null=True, upload_to='fotos_vtr/', verbose_name='Foto de Avaria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists_assinados', to=settings.AUTH_USER_MODEL)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='plantao.equipeplantao')),
            ],
            options={
                'verbose_name': 'Status do Checklist',
                'verbose_name_plural': 'Status dos Checklists',
                'db_table': 'plantao_checklist_status',
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=100, unique=True)),
                ('responsavel_grupo', models.ForeignKey(blank=True, help_text='Grupo responsável pelo checklist deste item (ex: Médico, Condutor)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Grupo Responsável')),
            ],
            options={
                'verbose_name': 'Item de Inventário',
                'verbose_name_plural': 'Itens de Inventário',
                'db_table': 'plantao_item_inventario',
            },
        ),
        migrations.CreateModel(
            name='ChecklistDetalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('status_alerta', models.CharField(blank=True, choices=[('VERDE', 'Verde'), ('AMARELO', 'Amarelo'), ('VERMELHO', 'Vermelho')], max_length=20, null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='plantao.checkliststatus')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_checklist', to='plantao.iteminventario')),
            ],
            options={
                'verbose_name': 'Detalhe do Checklist',
                'verbose_name_plural': 'Detalhes do Checklist',
                'db_table': 'plantao_checklist_detalhe',
                'unique_together': {('checklist', 'item')},
            },
        ),
    ]
