# Generated by Django 5.2.7 on 2025-11-02 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('I', 'Não Informado')], max_length=1)),
                ('is_gestante', models.BooleanField(default=False)),
                ('is_psiquiatrico', models.BooleanField(default=False)),
                ('is_paliativo', models.BooleanField(default=False)),
                ('recusa_atendimento', models.BooleanField(default=False)),
                ('foto_recusa', models.ImageField(blank=True, null=True, upload_to='fotos_recusa/')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='ocorrencias.ocorrencia')),
            ],
            options={
                'db_table': 'pacientes_paciente',
            },
        ),
        migrations.CreateModel(
            name='DadosEspecificosPaciente',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dados_especificos', serialize=False, to='pacientes.paciente')),
                ('idade_gestacional', models.CharField(blank=True, max_length=50, null=True)),
                ('perdas', models.BooleanField(blank=True, null=True)),
                ('sangramento', models.BooleanField(blank=True, null=True)),
                ('cartao_pre_natal', models.BooleanField(blank=True, null=True)),
                ('movimentos_fetais', models.BooleanField(blank=True, null=True)),
                ('contato_responsavel', models.CharField(blank=True, max_length=50, null=True)),
                ('faz_tratamento', models.BooleanField(blank=True, null=True)),
                ('observacoes_psiquiatricas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dado Específico do Paciente',
                'verbose_name_plural': 'Dados Específicos dos Pacientes',
                'db_table': 'pacientes_dados_especificos_paciente',
            },
        ),
        migrations.CreateModel(
            name='InformacaoClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravidade_cor', models.CharField(blank=True, max_length=20, null=True)),
                ('gravidade_texto', models.CharField(blank=True, max_length=20, null=True)),
                ('pressao_arterial', models.CharField(blank=True, max_length=10, null=True)),
                ('frequencia_cardiaca', models.PositiveIntegerField(blank=True, null=True)),
                ('frequencia_respiratoria', models.CharField(blank=True, max_length=20, null=True)),
                ('eva_dor', models.PositiveIntegerField(blank=True, null=True, verbose_name='Escala Visual de Dor (EVA)')),
                ('glasgow_total', models.PositiveIntegerField(blank=True, null=True)),
                ('cincinnati_status', models.CharField(blank=True, max_length=50, null=True)),
                ('mallampati_classe', models.CharField(blank=True, max_length=10, null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_clinica', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Informação Clínica',
                'verbose_name_plural': 'Informações Clínicas',
                'db_table': 'pacientes_informacao_clinica',
            },
        ),
        migrations.CreateModel(
            name='PertencesPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_pertences', models.TextField(blank=True, null=True)),
                ('valores_encontrados', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('entregue_para', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_pertences', models.ImageField(blank=True, null=True, upload_to='fotos_pertences/')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pertences', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Pertences do Paciente',
                'verbose_name_plural': 'Pertences dos Pacientes',
                'db_table': 'pacientes_pertences_paciente',
            },
        ),
    ]
