# Generated by Django 5.2.7 on 2025-11-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApoioOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtr_apoio_sigla', models.CharField(max_length=20, verbose_name='Sigla VTR Apoio')),
                ('data_hora_apoio', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Apoio de Ocorrência',
                'verbose_name_plural': 'Apoios de Ocorrências',
                'db_table': 'ocorrencias_apoio_ocorrencia',
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.TextField()),
                ('bairro', models.CharField(max_length=50)),
                ('foto_local', models.ImageField(blank=True, null=True, upload_to='fotos_locais/')),
                ('meios_acionados', models.TextField(blank=True, null=True)),
                ('info_transito', models.TextField(blank=True, null=True, verbose_name='Informações DPVAT')),
                ('link_gps', models.URLField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
                'db_table': 'ocorrencias_localizacao',
            },
        ),
        migrations.CreateModel(
            name='MaterialUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_usada', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Material Utilizado',
                'verbose_name_plural': 'Materiais Utilizados',
                'db_table': 'ocorrencias_material_utilizado',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_reg_central', models.CharField(max_length=20, unique=True, verbose_name='Nº Registro Central')),
                ('data_hora_inicio', models.DateTimeField()),
                ('tipo_ocorrencia', models.TextField()),
                ('status_final', models.CharField(max_length=50)),
                ('data_hora_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('finalizada', models.BooleanField(default=False)),
                ('observacoes_audio', models.FileField(blank=True, null=True, upload_to='audios_ocorrencias/')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'db_table': 'ocorrencias_ocorrencia',
            },
        ),
    ]
