# Generated by Django 5.2.7 on 2025-11-02 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocorrencias', '0001_initial'),
        ('plantao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apoioocorrencia',
            name='equipe_apoio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apoios_prestados', to='plantao.equipeplantao'),
        ),
        migrations.AddField(
            model_name='materialutilizado',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_em_ocorrencias', to='plantao.iteminventario'),
        ),
        migrations.AddField(
            model_name='materialutilizado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiais_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='plantao.equipeplantao'),
        ),
        migrations.AddField(
            model_name='materialutilizado',
            name='ocorrencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_utilizados', to='ocorrencias.ocorrencia'),
        ),
        migrations.AddField(
            model_name='localizacao',
            name='ocorrencia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localizacao', to='ocorrencias.ocorrencia'),
        ),
        migrations.AddField(
            model_name='apoioocorrencia',
            name='ocorrencia_mestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viaturas_apoio', to='ocorrencias.ocorrencia'),
        ),
    ]
